# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

app_keys: &app_keys
  github_key: <%= ENV['GITHUB_KEY'] %>
  github_secret: <%= ENV['GITHUB_SECRET'] %>
  aws_access: <%= ENV['AWS_ACCESS'] %>
  aws_secret: <%= ENV['AWS_SECRET'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  gauges_id: <%= ENV['GAUGES_ID'] %>
  google_analytics_id: <%= ENV['GOOGLE_ANALYTICS_ID'] %>
  party_foul_token: <%= ENV['PARTY_FOUL_TOKEN'] %>
  airbrake_key: <%= ENV['AIRBRAKE_KEY'] %>

development: &development
  <<: *app_keys
  secret_key_base: 80eeca7ca46a7b2424eaeca07eaa5012f87e36b302feff1a2b99de9ce51d0757daf440983df1ad10ef044271f1cbebfe78145527e8ac06d0c0a3a4f8a71e9a6e

test:
  <<: *development
  secret_key_base: 12104f112873b4c69355d12418cc2a954903de25ad29052bc22ba28936ce14909e2f87f073bf262ee09d7aa2309e3ee091fa538c256ebaf0ced98458a78e4763

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *app_keys
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  asset_host: <%= ENV["ASSETS_HOST"] %>

